# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|

    config.vm.define "consul-server" do |node|
      node.vm.provider "virtualbox" do |vb|
        vb.cpus = 1
        vb.memory = 2048
      end
      node.vm.hostname = "lx-consul-server"
      node.vm.box = "ubuntu/focal64" 
      node.vm.network "private_network", ip: "192.168.56.5"

      node.vm.network "forwarded_port", guest: 8500, host: 8500

      node.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update
        wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
        sudo apt update && sudo apt install consul
        consul --version      
      SHELL